"""empty message

Revision ID: 3ab9be92efb6
Revises: 723be3aeab72
Create Date: 2020-01-24 12:07:06.949861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab9be92efb6'
down_revision = '723be3aeab72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('post_tags')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'slug')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.VARCHAR(length=64), nullable=True))
    op.add_column('posts', sa.Column('slug', sa.VARCHAR(length=100), nullable=True))
    op.add_column('posts', sa.Column('status', sa.SMALLINT(), nullable=True))
    op.create_table('post_tags',
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
